version: 0.2

phases:
  build:
    commands:
      - mvn -Pnative native:compile -DskipTests
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/native-lambda-native.zip
cache:
  paths:
    - '/root/.m2/**/*'