version: 0.2

phases:
  build:
    commands:
      - mvn -DskipTests -Pnative clean package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/native-lambda-native.zip